<?php

namespace Caravane\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{

	


	public function findFromCurrentUser($user) {
		
		

		$qb = $this->createQueryBuilder('R');
		
		$qb->where('R.user = :user')
		->orderBy('R.name','ASC')
			  ->setParameter('user', $user);
				
		return $qb;
	}
}