imports:
    - { resource: parameters.yml }
    - { resource: parameters.facebook.ini }
    - { resource: parameters.twitter.ini }
    - { resource: parameters.google.ini }
    - { resource: security.yml }


services:
    my.facebook.user:
        class: Caravane\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
    my.twitter.user:
        class: Caravane\UserBundle\Security\User\Provider\TwitterProvider
        arguments:
            twitter_oauth: "@fos_twitter.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            session: "@session"
    my.google.user:
        class: Caravane\UserBundle\Security\User\Provider\GoogleProvider
        arguments:
            twitter_oauth: "@fos_google.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"






framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false
    globals:
        facebookLocale:          %facebookLocale%
        twitterCallbackUrl:          %twitterCallback_url%
    form:
        resources:
            - "BcBootstrapBundle:Form:form_div_layout.html.twig"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        sass:    ~
        compass: ~
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        lessphp:
          file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
          apply_to: "\.less$"

bc_bootstrap:
    less_filter: lessphp

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://127.0.0.1:27017
            options: {}
    default_database: xxxxxxxxxxxxxxxxxx
    document_managers:
        default:
            auto_mapping: true



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: mongodb # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Caravane\UserBundle\Document\User

fos_facebook:
      alias:  facebook
      app_id: %facebookAppId%
      secret: %facebookAppSecret%
      cookie: true
      permissions: [email,read_stream,user_photos]


fos_twitter:
        file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
        consumer_key: %twitterConsumer_key%
        consumer_secret:  %twitterConsumer_secret%
        callback_url:   %twitterCallback_url%

fos_google:
    app_name: %googleApp_name%
    client_id: %googleClient_id%
    client_secret: %googleClient_secret%
    state: auth
    access_type: online
    scopes: [userinfo.email, userinfo.profile]
    approval_prompt: auto
    callback_url: %googleCallback_url%
