parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: xxxxxxx
    database_user: xxxxxxx
    database_password: xxxxxxx
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: xxxxxxx
    database_path: null
