caravane_caravane_startup_edition:
    resource: "@CaravaneStartupEditionBundle/Controller/"
    type:     annotation
    prefix:   /

caravane_login:
    resource: "@CaravaneUserBundle/Controller/"
    type:     annotation
    prefix:   /login

login_google:
    pattern: /login/google
    defaults:  { _controller: FOSGoogleBundle:Security:login }
    options:
        expose: true


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


fos_login_fb_check:
    pattern:  /login_fb_check
    defaults:  { _controller: CaravaneUserBundle:Security:check }
    options:
        expose: true

fos_login_twitter_check:
    pattern:  /login_twitter_check
    defaults:  { _controller: CaravaneUserBundle:Security:check }
    options:
        expose: true

fos_login_google_check:
    pattern:  /login_google_check
    defaults:  { _controller: CaravaneUserBundle:Security:check }
    options:
        expose: true

fos_logout:
    pattern:  /logout
    defaults:  { _controller: CaravaneUserBundle:Security:logout }
    options:
        expose: true
